# Generated by Django 3.2.8 on 2023-11-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20231108_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Anio',
            field=models.CharField(max_length=60, verbose_name='Año'),
        ),
    ]
