# Generated by Django 3.2.8 on 2023-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_libro_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(max_length=255)),
                ('horario_atencion', models.CharField(max_length=100)),
                ('redes_sociales', models.URLField(blank=True)),
            ],
        ),
    ]
