# Generated by Django 3.2.8 on 2023-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fax',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
