# Generated by Django 3.2.8 on 2023-11-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_emprendimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
    ]
